version: '3'

name: swe2db

volumes:
    pgdata:

networks:
  external-nw:
    internal: false

services:
    database:
        image: postgres
        environment:
            - POSTGRES_USER=swe2
            - POSTGRES_PASSWORD=passw0rd
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - external-nw