-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Tour"
(
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    "Name" text NOT NULL,
    "From" text NOT NULL,
    "To" text NOT NULL,
    "TravellingType" text NOT NULL,
    PRIMARY KEY ("Id")
);
END;